### ISSUE TITLE
more detailed info about how to run this code

### ISSUE THREAD

**Issue by 943fansi** [adambelniak/WindForecast#4]
@MBelniak Thanks for your great work! I want to run this project, but failed.Could you give me more information about this command `python -m wind_forecast.main experiment=<experiment_yml_file> [options...]`?

**Comment by MBelniak** [comment]
Hi,
Sorry for the inconvenience. It's still WIP and I didn't really expect that anyone would try to run this project except for myself :D
I'll put more detailed info in the README.

Anyway,
`experiment_yml_file` is one of files in https://github.com/MBelniak/WindForecast/tree/master/src/wind_forecast/config/experiment
Without additional data you can try running an experiment without `_gfs` or `_cmax` suffixes. 
So, for transformer the command is `python -m wind_forecast.main experiment=transformer`. 
For options, look into https://github.com/MBelniak/WindForecast/blob/master/src/wind_forecast/config/experiment/__init__.py (e.g. `experiment.batch_size=32`) or https://github.com/MBelniak/WindForecast/blob/master/src/wind_forecast/config/lightning/__init__.py (e.g. `lightning.gpus=0`)

If you want to train models with GFS or CMAX radar data, use https://github.com/MBelniak/WindForecast/tree/master/src/gfs_archive_0_25 and https://github.com/MBelniak/WindForecast/blob/master/src/radar/fetch_radar_CMAX.py  to fetch the data first.

This project still doesn't run in 'prediction' setup, but it is planned.

If you have more questions don't hesitate to ask.

**Comment by MBelniak** [comment]
I've added information about creating conda environment and installing pip packages before running the project in the main repo README.
Basically:
```
conda env create -f environment.yml
pip install -r requirements.txt
```

**Comment by 943fansi** [comment]
> I've added information about creating conda environment and installing pip packages before running the project in the main repo README. Basically:
> 
> ```
> conda env create -f environment.yml
> pip install -r requirements.txt
> ```

Thanks.
